/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_ujikom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author lab.pplg
 */
public class FromLaporanTran extends javax.swing.JFrame {
    Connection konek;
    PreparedStatement pst;
    ResultSet rst;
    String tanggal,tanggal2,sql;
    /**
     * Creates new form FromLaporanTran
     */
    public FromLaporanTran() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        konek = Koneksi.koneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cari1 = new javax.swing.JButton();
        cari2 = new javax.swing.JButton();
        cari3 = new javax.swing.JButton();
        sebelumTanggal = new com.toedter.calendar.JDateChooser();
        dariTanggal = new com.toedter.calendar.JDateChooser();
        setelahTanggal = new com.toedter.calendar.JDateChooser();
        sampaiTanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataProduk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataTran = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sebelum tanggal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 140, 150, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Setelah tanggal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 240, 150, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Diantra tanggal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 190, 150, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("S/D");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 190, 23, 30);

        cari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imej/icons8-search-20.png"))); // NOI18N
        cari1.setText("Cari");
        cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1ActionPerformed(evt);
            }
        });
        getContentPane().add(cari1);
        cari1.setBounds(760, 140, 80, 27);

        cari2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imej/icons8-search-20.png"))); // NOI18N
        cari2.setText("Cari");
        cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2ActionPerformed(evt);
            }
        });
        getContentPane().add(cari2);
        cari2.setBounds(980, 190, 80, 27);

        cari3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imej/icons8-search-20.png"))); // NOI18N
        cari3.setText("Cari");
        cari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari3ActionPerformed(evt);
            }
        });
        getContentPane().add(cari3);
        cari3.setBounds(760, 240, 80, 27);
        getContentPane().add(sebelumTanggal);
        sebelumTanggal.setBounds(560, 140, 170, 30);
        getContentPane().add(dariTanggal);
        dariTanggal.setBounds(560, 190, 170, 30);
        getContentPane().add(setelahTanggal);
        setelahTanggal.setBounds(560, 240, 170, 30);
        getContentPane().add(sampaiTanggal);
        sampaiTanggal.setBounds(800, 190, 150, 30);

        tblDataProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DetailID", "ProdukID", "Harga", "JumlahProduk", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDataProduk);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 350, 550, 410);

        tblDataTran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PenjualanID", "DetailID", "TanggalPenjualan", "JamPenjualan", "TotalHarga"
            }
        ));
        tblDataTran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataTranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDataTran);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(730, 350, 550, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imej/Halamain dll.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
try {
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    tanggal = format.format(sebelumTanggal.getDate());
    sql = "select * from penjualan where TanggalPenjualan < '"+tanggal+"' ";
    pst = konek.prepareStatement(sql);
    rst = pst.executeQuery();
    tblDataTran.setModel(DbUtils.resultSetToTableModel(rst));
} catch (Exception e){
    JOptionPane.showMessageDialog(null, "Data Tidak Tampil");
}
// TODO add your handling code here:
    }//GEN-LAST:event_cari1ActionPerformed

    private void tblDataTranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataTranMouseClicked
try{
    int row = tblDataTran.getSelectedRow();
    String tableklik = (tblDataTran.getModel().getValueAt(row, 1).toString());
    String sql = "select * from detailpenjualan where DetailID=?";
    pst = konek.prepareStatement(sql);
    pst.setString(row, tableklik);
    rst = pst.executeQuery();
    tblDataTran.setModel(DbUtils.resultSetToTableModel(rst));
} catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataTranMouseClicked

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
try{
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    tanggal = format.format(dariTanggal.getDate());
    tanggal2 = format.format(sampaiTanggal.getDate());
    sql = "select * from penjualan where TanggalPenjualan between '"+tanggal+"' and '"+tanggal2+"' ";
    pst = konek.prepareStatement(sql);
    rst = pst.executeQuery();
    tblDataTran.setModel(DbUtils.resultSetToTableModel(rst));
} catch (Exception e){
    JOptionPane.showMessageDialog(null, "Data tidak Tampil");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_cari2ActionPerformed

    private void cari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari3ActionPerformed
try{
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    tanggal = format.format(setelahTanggal.getDate());
    sql = "select * from penjualan where TanggalPenjualan > '"+tanggal+"' ";
    pst = konek.prepareStatement(sql);
    rst = pst.executeQuery();
    tblDataTran.setModel(DbUtils.resultSetToTableModel(rst));
} catch (Exception e){
    JOptionPane.showMessageDialog(null, "Data tidak Tampil");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_cari3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromLaporanTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromLaporanTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromLaporanTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromLaporanTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromLaporanTran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari1;
    private javax.swing.JButton cari2;
    private javax.swing.JButton cari3;
    private com.toedter.calendar.JDateChooser dariTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser sampaiTanggal;
    private com.toedter.calendar.JDateChooser sebelumTanggal;
    private com.toedter.calendar.JDateChooser setelahTanggal;
    private javax.swing.JTable tblDataProduk;
    private javax.swing.JTable tblDataTran;
    // End of variables declaration//GEN-END:variables
}
